name: snow-observations-cookbook
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - numpy
  - scipy
  - matplotlib
  - rasterio
  - geopandas
  - xarray
  - pandas
  - shapely
  - rioxarray
  - earthaccess
  - seaborn
  - holoviews
  - bokeh
  - datashader
  - earthpy
  - pip 
  - contextily
  - h5netcdf
  - spectral
  - pip:
    - git+https://github.com/SnowEx/snowexsql.git@v1.1.0rc1
    - uavsar_pytools>=0.7.1, <0.8
    - snowmicropyn
    - metloom